---
- name: install a paackage based on os version
  hosts: all
  become: true
  tasks:
  - name: install yum packages
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHAT"
   
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "REDHAT"

  - name: install debian package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start a apache service
    service:
        name: apache2
        state: started
    when: ansible_os_family == "Debian"



