---

- name: this playboook is install package
  hosts: all
  become: true
  tasks:
  - name: install a apache2
    apt:
      name: apache2
      state: latest
  - name: start a apache service
    service:
      name: apache2
      state: started

