---
- name: this play is uninstalling the package based on os
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "REDHAT"

  - name: remove package
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "REDHAT"

  - name: stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
     

