---
- name: Create user and copy passwd file
  hosts: all
  tasks:
       - name: User creation
         user:
           name: kiran
           password: sunilsunil
           uid: 6779
           home: /home/kiran
       - name: Copy password into users home dir
         copy:
            src: /etc/passwd
            dest: /home/kiran
...
